spring.application.name=url-shortener-sb
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret = 95a4328d9060c7e5073e3c19d30ca437c8286f1ece1e651c5bf2d623721b502c19a2e24c76af08ece14d51b8ef8b5c49aa3acf2edb6e697dde382ba6dd67e807
jwt.expiration = 172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener = DEBUG